version: '3'
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
